# Copyright bysssss Corp. All Rights Reserved.

version: '2'

#networks:
  #basic:

networks:
  basic:
    external:
      name: net_basic

services:
  orderer.fabtest13.com:
    container_name: orderer.fabtest13.com
    image: hyperledger/fabric-orderer:1.3.0
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_basic
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP13
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/orderer0/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./configtx/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/fabtest13.com/orderers/orderer0.fabtest13.com/:/etc/hyperledger/crypto-config/orderer0
    networks:
      - basic
